apiVersion: v1
kind: Service
metadata:
  name: etcd
spec:
  type: NodePort
  selector:
    app: etcd
  ports:
    - name: client
      nodePort: 31015
      port: 2379
      protocol: TCP
      targetPort: client
    - name: peer
      port: 2380
      nodePort: 31018
      protocol: TCP
      targetPort: peer